namespace XaultWallet.Core.Models;

/// <summary>
/// Fund-safety policy for the Monero seed offset (a.k.a. seed-offset passphrase / "25th word").
///
/// A seed offset transforms the 25-word mnemonic into a DIFFERENT private spend key (the offset is
/// hashed and added to the seed scalar), so mnemonic-with-offset and mnemonic-alone are two
/// completely different wallets. That cuts two ways:
///
///   * An IMPORTED seed MAY carry an offset — the user is reproducing a wallet that was itself
///     created with that offset elsewhere. They must supply the SAME offset every time or they
///     silently open a different, empty wallet (the software cannot detect a wrong offset: any
///     seed + any offset is a structurally valid wallet).
///   * A GENERATED seed is created by monero-wallet-rpc with NO offset. Sealing a non-empty offset
///     next to it would make the later restore derive a DIFFERENT wallet than the address/seed we
///     showed at generation time === silent, permanent fund loss.
///
/// This class is the single choke point that enforces "an offset only ever accompanies an imported
/// seed." Route every WalletSecrets.SeedOffset assignment that comes from user input through it, so
/// the generated-seed foot-gun is impossible to reach regardless of UI state.
/// </summary>
public static class SeedOffsetPolicy
{
    /// <summary>
    /// The offset that is safe to seal for a seed. Returns the user's offset EXACTLY (byte-for-byte)
    /// for an IMPORTED seed, or an empty string for a GENERATED seed (which must never carry one).
    ///
    /// The imported offset is deliberately NOT trimmed or normalised. Monero applies
    /// <c>cn_slow_hash</c> to the raw offset bytes, so it is case- and whitespace-sensitive: trimming
    /// or case-folding it would derive a DIFFERENT wallet than the one the user created that
    /// passphrase with elsewhere. Unlike the mnemonic (a lowercase word list where whitespace is
    /// merely a separator), every byte of the offset is significant. We reproduce exactly what the
    /// user typed and rely on the UI to warn them it must match byte-for-byte.
    /// </summary>
    /// <param name="wasGenerated">True if the seed was generated by this app (never carries an offset).</param>
    /// <param name="userOffset">The offset the user typed (only meaningful when importing).</param>
    public static string ForSeed(bool wasGenerated, string? userOffset) =>
        wasGenerated ? string.Empty : (userOffset ?? string.Empty);
}
