using System.Security.Cryptography;
using System.Collections.ObjectModel;
using System.Text.RegularExpressions;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using XaultWallet.Core.Diagnostics;
using XaultWallet.Core.Models;
using XaultWallet.Core.Monero;
using XaultWallet.Core.Security;
// The VM's DaemonAddress *property* shadows the Core helper class of the same name.
using DaemonUrl = XaultWallet.Core.Monero.DaemonAddress;

namespace XaultWallet.Desktop.ViewModels;

/// <summary>
/// Add a wallet to the open vault: a new one (seed generated by monero-wallet-rpc, backed up and
/// checked like the first), or one restored from its seed, from its keys, or watch-only (address
/// and view key). Imports are opened by monero-wallet-rpc BEFORE they are saved — keys included,
/// which it checks against the address — and the resulting address is shown for the user to
/// recognise. It goes into whichever profile is open, decoy or not: the same rules for both.
/// </summary>
public sealed partial class AddWalletViewModel : ViewModelBase
{
    private readonly ProfileViewModel _profile;

    /// <summary>Cancelled when the user leaves this screen: what it started stops, adds nothing.</summary>
    private readonly CancellationTokenSource _leave = new();

    /// <summary>Its work was cancelled because the screen was left or the vault locked — nothing to report.</summary>
    private bool Abandoned => _leave.IsCancellationRequested || _profile.IsLocked;

    public AddWalletViewModel(ProfileViewModel profile)
    {
        _profile = profile;
        WalletSecrets? current = profile.Active is { } active
            ? profile.Profile.Wallets.FirstOrDefault(w => w.Id == active.WalletId)
            : profile.Profile.ActiveWallet;
        _name = $"Wallet {profile.Profile.Wallets.Count + 1}";
        _networkIndex = (int)(current?.Network ?? MoneroNetwork.Stagenet);
        _daemonAddress = current?.DaemonAddress ?? AppServices.Instance.DefaultDaemonAddress;
        _ = ProbeTestChainAsync(_daemonAddress);
    }

    /// <summary>Back without adding anything.</summary>
    public event Action? Cancelled;

    [RelayCommand]
    private void Cancel()
    {
        _leave.Cancel(); // a generation or import check still running stops, and adds nothing
        WipeSeed();
        Cancelled?.Invoke();
    }

    // ------------------------------------------------------------------ what kind

    /// <summary>0 new, 1 restore from seed, 2 restore from keys, 3 watch-only.</summary>
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsNew))]
    [NotifyPropertyChangedFor(nameof(IsSeedImport))]
    [NotifyPropertyChangedFor(nameof(IsKeyImport))]
    [NotifyPropertyChangedFor(nameof(IsWatchOnly))]
    [NotifyPropertyChangedFor(nameof(UsesKeys))]
    [NotifyPropertyChangedFor(nameof(IsImport))]
    private int _mode;

    public bool IsNew => Mode == 0;

    public bool IsSeedImport => Mode == 1;

    public bool IsKeyImport => Mode == 2;

    public bool IsWatchOnly => Mode == 3;

    public bool UsesKeys => Mode is 2 or 3;

    public bool IsImport => Mode != 0;

    partial void OnModeChanged(int value) => Error = string.Empty;

    // ------------------------------------------------------------------ name, network, node

    [ObservableProperty] private string _name;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsMainnet))]
    private int _networkIndex;

    public MoneroNetwork Network => (MoneroNetwork)NetworkIndex;

    [ObservableProperty] private string _daemonAddress;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsMainnet))]
    private bool _isLocalTestChain;

    /// <summary>Real funds: the mainnet warning shows (not for a local regtest chain).</summary>
    public bool IsMainnet => NetworkIndex == 0 && !IsLocalTestChain;

    public IReadOnlyList<RemoteNode> PresetNodes => RemoteNodes.All;

    [ObservableProperty] private RemoteNode? _selectedPreset;

    partial void OnSelectedPresetChanged(RemoteNode? value)
    {
        if (value is not null)
        {
            DaemonAddress = value.Url;
            NetworkIndex = value.NetworkIndex;
        }
    }

    partial void OnNetworkIndexChanged(int value)
    {
        // A seed generated against one network's tip must not be added on another (its restore
        // height means nothing there): generate again.
        WipeSeed();
        string port = value switch { 1 => "38081", 2 => "28081", _ => "18081" };
        string current = (DaemonAddress ?? string.Empty).Trim();
        if (current is "http://127.0.0.1:18081" or "http://127.0.0.1:38081" or "http://127.0.0.1:28081" or "")
        {
            DaemonAddress = $"http://127.0.0.1:{port}";
        }
    }

    private CancellationTokenSource? _chainProbe;

    partial void OnDaemonAddressChanged(string value) => _ = ProbeTestChainAsync(value);

    private async Task ProbeTestChainAsync(string address)
    {
        _chainProbe?.Cancel();
        var cts = _chainProbe = new CancellationTokenSource();
        try
        {
            await Task.Delay(350, cts.Token);
            bool testChain = await MoneroDiagnostics.IsLocalTestChainAsync(address, AppServices.Instance.Settings.ProxyAddress, cts.Token);
            if (!cts.IsCancellationRequested)
            {
                IsLocalTestChain = testChain;
            }
        }
        catch (OperationCanceledException)
        {
            // superseded by a newer address
        }
    }

    // ------------------------------------------------------------------ new wallet

    public ObservableCollection<SeedWord> SeedWords { get; } = new();

    [ObservableProperty] private bool _seedGenerated;
    [ObservableProperty] private bool _seedVerified;
    private string _mnemonic = string.Empty;
    private ulong _generatedHeight;
    private int[] _verifyIndices = Array.Empty<int>();

    [ObservableProperty] private string _verifyPrompt1 = string.Empty;
    [ObservableProperty] private string _verifyPrompt2 = string.Empty;
    [ObservableProperty] private string _verifyPrompt3 = string.Empty;
    [ObservableProperty] private string _verifyInput1 = string.Empty;
    [ObservableProperty] private string _verifyInput2 = string.Empty;
    [ObservableProperty] private string _verifyInput3 = string.Empty;
    [ObservableProperty] private string _verifyMessage = string.Empty;

    /// <summary>The backup check covers the words (typed from paper, not copied off the screen).</summary>
    [ObservableProperty] private bool _showVerifyOverlay;

    [RelayCommand]
    private void OpenVerify()
    {
        VerifyInput1 = VerifyInput2 = VerifyInput3 = VerifyMessage = string.Empty;
        ShowVerifyOverlay = true;
    }

    [RelayCommand]
    private void CloseVerify() => ShowVerifyOverlay = false;

    [RelayCommand]
    private async Task GenerateAsync()
    {
        Error = string.Empty;
        if (!DaemonUrl.IsValid(DaemonAddress))
        {
            Error = "The node must be an http(s) URL, e.g. http://127.0.0.1:18081.";
            return;
        }

        Busy = true;
        try
        {
            MoneroNetwork network = Network;
            string daemon = DaemonAddress.Trim();
            (string mnemonic, ulong height) = await _profile.RunWithBackendAsync(async ct =>
            {
                await using MoneroWalletService svc = AppServices.Instance.CreateWalletService();
                return await svc.GenerateNewSeedAsync(network, daemon, ct);
            }, _leave.Token);
            if (Network != network)
            {
                Error = "The network changed while the seed was being made. Generate it again.";
                return; // its restore height belongs to the other network's chain
            }

            _mnemonic = mnemonic;
            _generatedHeight = height;
            SeedWords.Clear();
            string[] words = mnemonic.Split(' ', StringSplitOptions.RemoveEmptyEntries);
            for (int i = 0; i < words.Length; i++)
            {
                SeedWords.Add(new SeedWord(i + 1, words[i]));
            }

            // Three random positions to type back: proof the seed was written down (CSPRNG).
            int[] order = Enumerable.Range(0, words.Length).ToArray();
            RandomNumberGenerator.Shuffle(order.AsSpan());
            _verifyIndices = order.Take(3).OrderBy(x => x).ToArray();
            VerifyPrompt1 = $"Word #{_verifyIndices[0] + 1}";
            VerifyPrompt2 = $"Word #{_verifyIndices[1] + 1}";
            VerifyPrompt3 = $"Word #{_verifyIndices[2] + 1}";
            VerifyInput1 = VerifyInput2 = VerifyInput3 = VerifyMessage = string.Empty;
            SeedVerified = false;
            SeedGenerated = true;
        }
        catch (OperationCanceledException) when (Abandoned)
        {
            // the screen was left, or the vault locked: nothing to show
        }
        catch (Exception ex)
        {
            Error = "Seed generation failed: " + ex.Message;
        }
        finally
        {
            Busy = false;
        }
    }

    [RelayCommand]
    private void VerifySeed()
    {
        string[] words = _mnemonic.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (_verifyIndices.Length != 3 || _verifyIndices.Any(i => i >= words.Length))
        {
            VerifyMessage = "Generate the seed first.";
            return;
        }

        SeedVerified =
            words[_verifyIndices[0]].Equals(VerifyInput1.Trim(), StringComparison.OrdinalIgnoreCase) &&
            words[_verifyIndices[1]].Equals(VerifyInput2.Trim(), StringComparison.OrdinalIgnoreCase) &&
            words[_verifyIndices[2]].Equals(VerifyInput3.Trim(), StringComparison.OrdinalIgnoreCase);
        VerifyMessage = SeedVerified ? string.Empty : "One or more words don't match. Check your written backup.";
        if (SeedVerified)
        {
            ShowVerifyOverlay = false;
        }
    }

    private void WipeSeed()
    {
        _mnemonic = string.Empty;
        _generatedHeight = 0;
        SeedWords.Clear();
        SeedGenerated = SeedVerified = ShowVerifyOverlay = false;
        _verifyIndices = Array.Empty<int>();
    }

    // ------------------------------------------------------------------ imports

    [ObservableProperty] private string _importMnemonic = string.Empty;
    [ObservableProperty] private string _importSeedOffset = string.Empty;
    [ObservableProperty] private string _importAddress = string.Empty;
    [ObservableProperty] private string _importViewKey = string.Empty;
    [ObservableProperty] private string _importSpendKey = string.Empty;

    /// <summary>0 full history (safe, slow), 1 from a block height.</summary>
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsSpecificHeight))]
    private int _restoreMode;

    public bool IsSpecificHeight => RestoreMode == 1;

    [ObservableProperty] private string _restoreHeightText = string.Empty;

    [GeneratedRegex("^[0-9a-fA-F]{64}$")]
    private static partial Regex HexKey();

    // ------------------------------------------------------------------ add

    [ObservableProperty] private string _error = string.Empty;
    [ObservableProperty] private bool _busy;

    /// <summary>"Is this your wallet?" — the address the import opened to.</summary>
    [ObservableProperty] private bool _showConfirm;
    [ObservableProperty] private string _confirmAddress = string.Empty;
    private WalletSecrets? _pending;

    [RelayCommand]
    private async Task AddAsync()
    {
        if (Busy || ShowConfirm)
        {
            return;
        }

        Error = string.Empty;
        string name = Name.Trim();
        if (name.Length is 0 or > ProfileViewModel.MaxNameLength)
        {
            Error = $"Give the wallet a name (up to {ProfileViewModel.MaxNameLength} characters).";
            return;
        }

        if (!DaemonUrl.IsValid(DaemonAddress))
        {
            Error = "The node must be an http(s) URL, e.g. http://127.0.0.1:18081.";
            return;
        }

        WalletSecrets? wallet = BuildWallet(name);
        if (wallet is null)
        {
            return; // Error set
        }

        if (Duplicate(wallet) is { } existing)
        {
            Error = $"That wallet is already in this vault, as “{existing}”.";
            return;
        }

        // What the wallet was built from, as it was when Add was pressed: the form stays live while the
        // node and the import check are asked, and must not change what happens next.
        bool isNew = IsNew;
        bool isSeedImport = IsSeedImport;
        bool fromHeight = RestoreMode == 1;

        Busy = true;
        try
        {
            // The same restore-height rules as the vault's first wallet (CreateWalletViewModel):
            // a generated seed scans from its own generation tip, never above the current tip; a
            // typed height above the tip would scan nothing and look like an empty wallet.
            ulong tip = await GetTipHeightAsync(wallet.DaemonAddress, _leave.Token);
            if (Abandoned)
            {
                return;
            }

            if (isNew)
            {
                wallet.RestoreHeight = wallet.RestoreHeight != 0
                    ? (tip == 0 ? wallet.RestoreHeight : Math.Min(wallet.RestoreHeight, tip))
                    : (tip == 0 ? 0 : RestoreHeights.ForNewSeed(tip, wallet.Network, DateTimeOffset.UtcNow));
                await SaveAsync(wallet); // generated by wallet-rpc and backed up: nothing to echo
                return;
            }

            if (fromHeight && tip > 0 && wallet.RestoreHeight > tip)
            {
                Error = $"Restore height {wallet.RestoreHeight:N0} is beyond the current chain tip ({tip:N0}). Check for a typo.";
                return;
            }

            // Open it in monero-wallet-rpc first: a bad seed or keys must never reach the vault.
            string address = await _profile.RunWithBackendAsync(async ct =>
            {
                await using MoneroWalletService svc = AppServices.Instance.CreateWalletService();
                return await svc.ValidateWalletOpensAsync(wallet, ct);
            }, _leave.Token);
            if (Abandoned)
            {
                return;
            }

            if (_profile.NameOfWalletWithAddress(address) is { } same)
            {
                Error = $"That wallet is already in this vault, as “{same}”.";
                return;
            }

            // Kept with the wallet (a seed's address too): the next import of the same wallet, by
            // seed or by keys, is recognised even before this one has been opened.
            wallet.Address = address;
            _pending = wallet;
            ConfirmAddress = address;
            ShowConfirm = true;
        }
        catch (FileNotFoundException)
        {
            Error = "monero-wallet-rpc isn't available, so the wallet can't be checked. Set it up in Settings first.";
        }
        catch (OperationCanceledException) when (Abandoned)
        {
            // the screen was left, or the vault locked: nothing to add, nothing to show
        }
        catch (Exception ex)
        {
            Error = $"That {(isSeedImport ? "seed" : "address and key combination")} doesn't open a wallet: {ex.Message}";
        }
        finally
        {
            Busy = false;
        }
    }

    [RelayCommand]
    private async Task ConfirmAddAsync()
    {
        ShowConfirm = false;
        WalletSecrets? wallet = _pending;
        _pending = null;
        if (wallet is not null)
        {
            Busy = true;
            try
            {
                await SaveAsync(wallet);
            }
            finally
            {
                Busy = false;
            }
        }
    }

    [RelayCommand]
    private void CancelConfirm()
    {
        ShowConfirm = false;
        _pending = null;
        ConfirmAddress = string.Empty;
    }

    private async Task SaveAsync(WalletSecrets wallet)
    {
        if (await _profile.AddAsync(wallet) is { } error)
        {
            Error = error;
            return;
        }

        WipeSeed();
        ImportMnemonic = ImportSeedOffset = ImportSpendKey = ImportViewKey = string.Empty;
        // The profile switched to the new wallet: the shell shows it.
    }

    /// <summary>The wallet as typed, or null with <see cref="Error"/> set.</summary>
    private WalletSecrets? BuildWallet(string name)
    {
        var wallet = new WalletSecrets
        {
            Name = name,
            Network = Network,
            DaemonAddress = DaemonAddress.Trim(),
            EphemeralWalletPassword = Convert.ToHexString(VaultCrypto.RandomBytes(24)),
        };

        if (IsNew)
        {
            if (!SeedGenerated)
            {
                Error = "Generate the seed first.";
                return null;
            }

            if (!SeedVerified)
            {
                Error = "Write the 25 words down, then type the three words asked for to check your backup.";
                return null;
            }

            wallet.Kind = WalletKind.Seed;
            wallet.Mnemonic = _mnemonic;
            wallet.SeedOffset = SeedOffsetPolicy.ForSeed(wasGenerated: true, string.Empty);
            wallet.RestoreHeight = _generatedHeight;
            return wallet;
        }

        ulong height = 0;
        if (RestoreMode == 1 && !BlockHeight.TryParse(RestoreHeightText, out height))
        {
            Error = "Enter the block height to scan from, e.g. 3150000 (or scan the full history).";
            return null;
        }

        wallet.RestoreHeight = height;

        if (IsSeedImport)
        {
            string mnemonic = string.Join(' ', ImportMnemonic.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries)).ToLowerInvariant();
            int words = mnemonic.Length == 0 ? 0 : mnemonic.Split(' ').Length;

            // What monero-wallet-rpc's restore accepts (electrum-words.cpp: 25 words, or the old
            // 24 without the checksum word, or 12); it checks the words themselves.
            if (words is not (25 or 24 or 12))
            {
                Error = $"A Monero seed is 25 words; this one has {words}.";
                return null;
            }

            wallet.Kind = WalletKind.Seed;
            wallet.Mnemonic = mnemonic;
            wallet.SeedOffset = SeedOffsetPolicy.ForSeed(wasGenerated: false, ImportSeedOffset);
            return wallet;
        }

        string address = ImportAddress.Trim();
        if (MoneroAddress.Problem(address, Network) is { } problem)
        {
            Error = problem;
            return null;
        }

        if (address.Length != 95 || !IsStandardAddress(address, Network))
        {
            Error = "Use the wallet's main address (it starts with " + StandardPrefix(Network) + "), not a subaddress or an integrated address.";
            return null;
        }

        if (!HexKey().IsMatch(ImportViewKey.Trim()))
        {
            Error = "The private view key is 64 hexadecimal characters.";
            return null;
        }

        wallet.Address = address;
        wallet.ViewKey = ImportViewKey.Trim().ToLowerInvariant();
        if (IsWatchOnly)
        {
            wallet.Kind = WalletKind.ViewOnly;
            return wallet;
        }

        if (!HexKey().IsMatch(ImportSpendKey.Trim()))
        {
            Error = "The private spend key is 64 hexadecimal characters.";
            return null;
        }

        wallet.Kind = WalletKind.Keys;
        wallet.SpendKey = ImportSpendKey.Trim().ToLowerInvariant();
        return wallet;
    }

    private static string StandardPrefix(MoneroNetwork network) => network switch
    {
        MoneroNetwork.Stagenet => "5",
        MoneroNetwork.Testnet => "9",
        _ => "4",
    };

    private static bool IsStandardAddress(string address, MoneroNetwork network) =>
        address.StartsWith(StandardPrefix(network), StringComparison.Ordinal);

    /// <summary>The name of a wallet in this profile that is the same wallet, if any. A seed with a
    /// different offset is a different wallet; across kinds (seed vs keys), the address the import
    /// opens to is compared after validation.</summary>
    private string? Duplicate(WalletSecrets candidate)
    {
        foreach (WalletSecrets w in _profile.Profile.Wallets)
        {
            // The same seed on another network is another wallet (other addresses, other funds).
            bool sameSeed = candidate.Mnemonic.Length > 0
                && w.Network == candidate.Network
                && string.Equals(NormalizeWords(w.Mnemonic), candidate.Mnemonic, StringComparison.Ordinal)
                && string.Equals(w.SeedOffset, candidate.SeedOffset, StringComparison.Ordinal);
            bool sameAddress = candidate.Address.Length > 0 && string.Equals(w.Address, candidate.Address, StringComparison.Ordinal);
            if (sameSeed || sameAddress)
            {
                return w.Name;
            }
        }

        return null;
    }

    private static string NormalizeWords(string words) =>
        string.Join(' ', words.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries)).ToLowerInvariant();

    /// <summary>The node's height, or 0 when it can't be reached or doesn't answer in time (a full scan
    /// is never wrong) — or when <paramref name="ct"/> stops the wait, which the caller checks.</summary>
    private static async Task<ulong> GetTipHeightAsync(string daemon, CancellationToken ct)
    {
        try
        {
            return await MoneroDiagnostics.ProbeDaemonAsync(daemon, AppServices.Instance.Settings.ProxyAddress, ct);
        }
        catch
        {
            return 0; // unreachable, not a Monero node, or no answer in time
        }
    }
}
